name: "DOC - Build and deploy"
on:
  push:
    branches:
      - master
    paths:
      - "**/build.py"
      - "docs/**"
      - "**.yml"
      - "**.md"
      - "**.json"

jobs:
  # Skip checks: https://github.com/fkirc/skip-duplicate-actions#option-3-cancellation-only
  skip_checks:
    name: Skip checks
    runs-on: ubuntu-latest
    if: github.repository == 'nvuillam/mega-linter'
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'nvuillam/mega-linter'
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mdx_truly_sane_lists json-schema-for-humans
      - run: cd .automation && bash build_schemas_doc.sh && cd ..
      - run: mkdocs gh-deploy --force
