---
#########################
#########################
## Deploy Docker Image ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: "Build & Deploy - RELEASE"
on:
  release:
    # Want to run the automation when a release is created
    types: ["created"]
    paths:
      - "Dockerfile"
      - "megalinter/**"
      - "mega-linter-runner/**"
      - "flavors/**"
      - "**/linter-versions.json"

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Deploy Docker Image - RELEASE
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Only run on main repo
    if: github.repository == 'nvuillam/mega-linter' && !contains(github.event.head_commit.message, 'skip deploy')
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      ########################################################
      # Publish updated version of mega-linter-runner on NPM #
      ########################################################
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: cd mega-linter-runner && npm install
      - run: cd mega-linter-runner && npm publish || echo "mega-linter-runner not published"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      ###################################
      # Run Deploy script for Dockerhub #
      ###################################
      - name: Deploy Release image to Dockerhub
        env:
          # Set the Env Vars
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_REPO: nvuillam/mega-linter
          IMAGE_VERSION: ${{ github.event.release.tag_name }}
          DOCKERFILE_PATH: Dockerfile
          REGISTRY: Docker
        shell: bash
        run: .automation/upload-docker.sh

      ###################################################
      # Run Deploy script for GitHub Container Registry #
      ###################################################
      - name: Deploy Release image to GitHub Container Registry
        env:
          # Set the Env Vars
          GCR_USERNAME: ${{ secrets.GCR_USERNAME }}
          GCR_TOKEN: ${{ secrets.GCR_PASSWORD }}
          IMAGE_REPO: nvuillam/mega-linter
          IMAGE_VERSION: ${{ github.event.release.tag_name }}
          DOCKERFILE_PATH: Dockerfile
          REGISTRY: GCR
        shell: bash
        run: .automation/upload-docker.sh

      # Free disk space
      - name: Free Disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET

      ##############################################
      # Check Docker image security with Trivy #
      ##############################################
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.1.0
        with:
          image-ref: "docker.io/nvuillam/mega-linter:${{ github.event.release.tag_name }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
