---
name: "Test mega-linter-runner"
on: [push, pull_request]

jobs:
  # Skip checks: https://github.com/fkirc/skip-duplicate-actions#option-3-cancellation-only
  skip_checks:
    name: Skip checks
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

  build:
    name: Test Mega-Linter runner
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Prevent duplicate run from happening when a forked push is committed
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    timeout-minutes: 60
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v3.4.0
        with:
          node-version: "12"
      - name: Install dependencies
        run: cd mega-linter-runner && npm ci && npm link
      - name: Run tests
        run: cd mega-linter-runner && npm run test
